In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel('Customer Call List.xlsx')

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
 data=data.drop_duplicates()

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
data['Last_Name']=data['Last_Name'].str.strip('._/')

/tmp/ipython-input-2385633673.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Last_Name']=data['Last_Name'].str.strip('._/')

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
data['Phone_Number']=data['Phone_Number'].astype(str).replace('[^a-zA-Z0-9]','',regex=True)

/tmp/ipython-input-2521191406.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Phone_Number']=data['Phone_Number'].astype(str).replace('[^a-zA-Z0-9]','',regex=True)

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,nan,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
data['Phone_Number']=data['Phone_Number'].apply(lambda x:x[0:3]+'-' + x[3:6]+'-' +x[6:])

/tmp/ipython-input-259110304.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Phone_Number']=data['Phone_Number'].apply(lambda x:x[0:3]+'-' + x[3:6]+'-' +x[6:])

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na--,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
data['Phone_Number'].fillna('')

0     123-545-5421
1     123-643-9775
2     706-695-0392
3     123-543-2345
4     876-678-3469
5     304-762-2467
6            nan--
7     876-678-3469
8             Na--
9     123-545-5421
10           nan--
11    706-695-0392
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17    706-695-0392
18            Na--
19    876-678-3469
Name: Phone_Number, dtype: object

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na--,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
data['Phone_Number']=data['Phone_Number'].str.replace('Na--','')

/tmp/ipython-input-3402187988.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Phone_Number']=data['Phone_Number'].str.replace('Na--','')

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
data[['street','city','pincode']] = data['Address'].str.split(',',expand=True)

/tmp/ipython-input-766010650.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['street','city','pincode']] = data['Address'].str.split(',',expand=True)
/tmp/ipython-input-766010650.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['street','city','pincode']] = data['Address'].str.split(',',expand=True)
/tmp/ipython-input-766010650.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['street','city','pincode']] = data['Address'].str.split(',',expand=True)

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street,city,pincode
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [ ]:
data=data.drop(columns=['Address','city','pincode','Not_Useful_Column'])

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street
2,1003,Walter,White,706-695-0392,N,NaN,298 Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway
6,1007,Jeff,Winger,nan--,No,No,1209 South Street
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street
10,1011,Samwise,Gamgee,nan--,Yes,No,612 Shire Lane
11,1012,Harry,Potter,706-695-0392,Y,NaN,2394 Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway
14,1015,Toby,Flenderson,304-762-2467,N,No,214 HR Avenue
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498 Super Lane
18,1019,Creed,Braton,,N/a,Yes,N/a
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road

In [ ]:
data['Paying Customer']=data['Paying Customer'].str.replace("Y",'Yes')

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street
2,1003,Walter,White,706-695-0392,No,NaN,298 Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue
4,1005,Jon,Snow,876-678-3469,Yes,N,123 Dragons Road
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway
6,1007,Jeff,Winger,nan--,No,N,1209 South Street
7,1008,Sherlock,Holmes,876-678-3469,No,N,98 Clue Drive
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street
10,1011,Samwise,Gamgee,nan--,Yes,N,612 Shire Lane
11,1012,Harry,Potter,706-695-0392,Yes,NaN,2394 Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway
14,1015,Toby,Flenderson,304-762-2467,No,N,214 HR Avenue
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue
17,1018,Clark,Kent,706-695-0392,Yes,NaN,3498 Super Lane
18,1019,Creed,Braton,,No,Yes,N/a
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road

In [ ]:
data['Do_Not_Contact']=data['Do_Not_Contact'].str.replace("Y",'Yes')

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street
2,1003,Walter,White,706-695-0392,No,NaN,298 Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,Yes,Yes,980 Paper Avenue
4,1005,Jon,Snow,876-678-3469,Yes,No,123 Dragons Road
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway
6,1007,Jeff,Winger,nan--,No,No,1209 South Street
7,1008,Sherlock,Holmes,876-678-3469,No,No,98 Clue Drive
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street
10,1011,Samwise,Gamgee,nan--,Yes,No,612 Shire Lane
11,1012,Harry,Potter,706-695-0392,Yes,NaN,2394 Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,Yes,No,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway
14,1015,Toby,Flenderson,304-762-2467,No,No,214 HR Avenue
15,1016,Ron,Weasley,123-545-5421,No,No,2395 Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue
17,1018,Clark,Kent,706-695-0392,Yes,NaN,3498 Super Lane
18,1019,Creed,Braton,,No,Yes,N/a
19,1020,Anakin,Skywalker,876-678-3469,Yes,No,910 Tatooine Road

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street
2,1003,Walter,White,706-695-0392,No,NaN,298 Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,Yes,Yes,980 Paper Avenue
4,1005,Jon,Snow,876-678-3469,Yes,No,123 Dragons Road
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway
6,1007,Jeff,Winger,nan--,No,No,1209 South Street
7,1008,Sherlock,Holmes,876-678-3469,No,No,98 Clue Drive
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street
10,1011,Samwise,Gamgee,nan--,Yes,No,612 Shire Lane
11,1012,Harry,Potter,706-695-0392,Yes,NaN,2394 Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,Yes,No,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway
14,1015,Toby,Flenderson,304-762-2467,No,No,214 HR Avenue
15,1016,Ron,Weasley,123-545-5421,No,No,2395 Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue
17,1018,Clark,Kent,706-695-0392,Yes,NaN,3498 Super Lane
18,1019,Creed,Braton,,No,Yes,N/a
19,1020,Anakin,Skywalker,876-678-3469,Yes,No,910 Tatooine Road

In [ ]:
data['Do_Not_Contact']=data['Do_Not_Contact'].fillna('Yes')

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street
2,1003,Walter,White,706-695-0392,No,Yes,298 Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,Yes,Yes,980 Paper Avenue
4,1005,Jon,Snow,876-678-3469,Yes,No,123 Dragons Road
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway
6,1007,Jeff,Winger,nan--,No,No,1209 South Street
7,1008,Sherlock,Holmes,876-678-3469,No,No,98 Clue Drive
8,1009,Gandalf,NaN,,Yes,Yes,123 Middle Earth
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street
10,1011,Samwise,Gamgee,nan--,Yes,No,612 Shire Lane
11,1012,Harry,Potter,706-695-0392,Yes,Yes,2394 Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,Yes,No,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway
14,1015,Toby,Flenderson,304-762-2467,No,No,214 HR Avenue
15,1016,Ron,Weasley,123-545-5421,No,No,2395 Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue
17,1018,Clark,Kent,706-695-0392,Yes,Yes,3498 Super Lane
18,1019,Creed,Braton,,No,Yes,N/a
19,1020,Anakin,Skywalker,876-678-3469,Yes,No,910 Tatooine Road

In [ ]:
for i in data.index:
  if data.loc[i,'Do_Not_Contact']=='Yes':
    data.drop(i,inplace=True)

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane
4,1005,Jon,Snow,876-678-3469,Yes,No,123 Dragons Road
6,1007,Jeff,Winger,nan--,No,No,1209 South Street
7,1008,Sherlock,Holmes,876-678-3469,No,No,98 Clue Drive
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street
10,1011,Samwise,Gamgee,nan--,Yes,No,612 Shire Lane
12,1013,Don,Draper,123-543-2345,Yes,No,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway
14,1015,Toby,Flenderson,304-762-2467,No,No,214 HR Avenue
15,1016,Ron,Weasley,123-545-5421,No,No,2395 Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue
19,1020,Anakin,Skywalker,876-678-3469,Yes,No,910 Tatooine Road

In [ ]:

for i in data.index:
  if data.loc[i,'Paying Customer']=='No':
    data.drop(i,inplace=True)

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane
4,1005,Jon,Snow,876-678-3469,Yes,No,123 Dragons Road
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street
10,1011,Samwise,Gamgee,nan--,Yes,No,612 Shire Lane
12,1013,Don,Draper,123-543-2345,Yes,No,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue
19,1020,Anakin,Skywalker,876-678-3469,Yes,No,910 Tatooine Road

In [ ]:
for i in data.index:
  if data.loc[i,'Phone_Number']=='nan--':
    data.drop(i,inplace=True)

In [ ]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane
4,1005,Jon,Snow,876-678-3469,Yes,No,123 Dragons Road
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street
12,1013,Don,Draper,123-543-2345,Yes,No,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue
19,1020,Anakin,Skywalker,876-678-3469,Yes,No,910 Tatooine Road

In [ ]:
data.shape

(7, 7)

In [ ]:
data.to_excel('Cleaned Customer Call List.xlsx')