In [15]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dirty_cafe_sales.csv')

In [3]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [5]:
df['Item'].value_counts()

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64

In [6]:
df['Item']=df['Item'].str.replace('ERROR','NaN')

In [7]:
df['Item']=df['Item'].str.replace('UNKNOWN','NaN')

In [14]:
df['Item'].value_counts()

Item
Juice       1504
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
NaN          636
Name: count, dtype: int64

In [16]:
df['Item'].replace('NaN', np.nan, inplace=True)

In [17]:
df['Item'].fillna(df['Item'].mode()[0], inplace=True)

In [19]:
df['Item'].value_counts()

Item
Juice       2140
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
Name: count, dtype: int64

In [20]:
df['Quantity'].value_counts()

Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64

In [21]:
df['Quantity'].replace('ERROR',np.nan, inplace=True)

In [22]:
df['Quantity'].replace('UNKNOWN',np.nan, inplace=True)

In [31]:
df['Quantity']=df['Quantity'].astype(float)

In [32]:
df['Quantity'].dtype

dtype('float64')

In [34]:
df['Quantity'].fillna(df['Quantity'].mean(), inplace=True)

C:\Users\sheik\AppData\Local\Temp\ipykernel_14012\487214857.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(df['Quantity'].mean(), inplace=True)

In [35]:
df['Quantity'].value_counts()

Quantity
5.000000    2013
2.000000    1974
4.000000    1863
3.000000    1849
1.000000    1822
3.028463     479
Name: count, dtype: int64

In [36]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,Juice,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [37]:
df['Price Per Unit'].value_counts()

Price Per Unit
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
UNKNOWN     164
Name: count, dtype: int64

In [38]:
df['Price Per Unit'].replace('ERROR',np.nan, inplace=True)

In [39]:
df['Price Per Unit'].replace('UNKNOWN',np.nan, inplace=True)

In [40]:
df['Price Per Unit'].value_counts()

Price Per Unit
3.0    2429
4.0    2331
2.0    1227
5.0    1204
1.0    1143
1.5    1133
Name: count, dtype: int64

In [44]:
df['Price Per Unit']=df['Price Per Unit'].astype(float)

In [45]:
df['Price Per Unit'].fillna(df['Price Per Unit'].mean(), inplace=True)

C:\Users\sheik\AppData\Local\Temp\ipykernel_14012\3852671811.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price Per Unit'].fillna(df['Price Per Unit'].mean(), inplace=True)

In [49]:
df['Price Per Unit']=df['Price Per Unit'].round(1)

In [50]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [52]:
df['Total Spent'].value_counts()

Total Spent
6.0        979
12.0       939
3.0        930
4.0        923
20.0       746
15.0       734
8.0        677
10.0       524
2.0        497
9.0        479
5.0        468
16.0       444
25.0       259
7.5        237
1.0        232
4.5        225
1.5        205
UNKNOWN    165
ERROR      164
Name: count, dtype: int64

In [53]:
df['Total Spent'].replace('ERROR',np.nan, inplace=True)

In [54]:
df['Total Spent'].replace('UNKNOWN',np.nan, inplace=True)

In [55]:
df['Total Spent'].value_counts()

Total Spent
6.0     979
12.0    939
3.0     930
4.0     923
20.0    746
15.0    734
8.0     677
10.0    524
2.0     497
9.0     479
5.0     468
16.0    444
25.0    259
7.5     237
1.0     232
4.5     225
1.5     205
Name: count, dtype: int64

In [59]:
df['Total Spent']=df['Total Spent'].astype(float)

In [60]:
df['Total Spent'].dtype

dtype('float64')

In [62]:
df['Total Spent'].fillna(df['Total Spent'].mean(), inplace=True)

In [65]:
df['Total Spent']=df['Total Spent'].round(1)

In [66]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [67]:
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [68]:
df['Payment Method'].replace('ERROR',np.nan, inplace=True)

In [69]:
df['Payment Method'].replace('UNKNOWN',np.nan, inplace=True)

In [70]:
df['Payment Method'].fillna(df['Payment Method'].mode()[0], inplace=True)

In [71]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,UNKNOWN,2023-08-30
9996,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [72]:
df['Location'].value_counts()

Location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [74]:
df['Location'].replace('ERROR',np.nan, inplace=True)

In [75]:
df['Location'].replace('UNKNOWN',np.nan, inplace=True)

In [76]:
df['Location'].fillna(df['Location'].mode()[0],inplace=True)

In [77]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway,2023-08-30
9996,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,Takeaway,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway,2023-03-02
9998,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [82]:
df['Transaction Date']=pd.to_datetime(df['Transaction Date'], errors='coerce')

In [86]:
df['Transaction Date'].value_counts()

Transaction Date
2023-06-16    40
2023-02-06    40
2023-09-21    39
2023-03-13    39
2023-07-24    39
              ..
2023-11-24    15
2023-04-27    15
2023-07-22    14
2023-03-11    14
2023-02-17    14
Name: count, Length: 365, dtype: int64

In [84]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway,2023-08-30
9996,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,Takeaway,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway,2023-03-02
9998,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
df['Transaction Date'].isna().sum()

np.int64(460)

In [89]:
df=df.dropna(subset=['Transaction Date'])

In [90]:
df['Transaction Date'].isna().sum()

np.int64(0)

In [91]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway,2023-08-30
9996,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,Takeaway,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway,2023-03-02
9998,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [93]:
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    5212
Credit Card       2170
Cash              2158
Name: count, dtype: int64

In [97]:
df['Transaction Date']=df['Transaction Date'].astype(str)

C:\Users\sheik\AppData\Local\Temp\ipykernel_14012\3776584724.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Transaction Date']=df['Transaction Date'].astype(str)

In [100]:
df['Transaction Date']=df['Transaction Date'].str.replace('-','')

C:\Users\sheik\AppData\Local\Temp\ipykernel_14012\3375234070.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Transaction Date']=df['Transaction Date'].str.replace('-','')

In [101]:
df['Transaction Date'].value_counts()

Transaction Date
20230616    40
20230206    40
20230921    39
20230313    39
20230724    39
            ..
20231124    15
20230427    15
20230722    14
20230311    14
20230217    14
Name: count, Length: 365, dtype: int64

In [103]:
df['Transaction Date']=df['Transaction Date'].apply(lambda x :x[0:4]+'-' + x[4:6]+'-' + x[6:])

C:\Users\sheik\AppData\Local\Temp\ipykernel_14012\145912463.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Transaction Date']=df['Transaction Date'].apply(lambda x :x[0:4]+'-' + x[4:6]+'-' + x[6:])

In [104]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway,2023-08-30
9996,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,Takeaway,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway,2023-03-02
9998,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [106]:
df.iloc[:6,:]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,Takeaway,2023-03-31

In [110]:
df.loc[:6,'Item']

0      Coffee
1        Cake
2      Cookie
3       Salad
4      Coffee
5    Smoothie
6       Juice
Name: Item, dtype: object

In [111]:
df.set_index('Transaction Date', inplace=True)

In [112]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
Transaction Date,,,,,,,
2023-09-08,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway
2023-05-16,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store
2023-07-19,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store
2023-04-27,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway
2023-06-11,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store
...,...,...,...,...,...,...,...
2023-08-30,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway
2023-06-02,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,Takeaway
2023-03-02,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway
2023-12-02,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway
2023-11-07,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store

In [116]:
df.reset_index(inplace=True)

In [117]:
df

,Transaction Date,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
0,2023-09-08,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway
1,2023-05-16,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store
2,2023-07-19,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store
3,2023-04-27,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway
4,2023-06-11,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store
...,...,...,...,...,...,...,...,...
9535,2023-08-30,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway
9536,2023-06-02,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,Takeaway
9537,2023-03-02,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway
9538,2023-12-02,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway
9539,2023-11-07,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store

In [118]:
df

,Transaction Date,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
0,2023-09-08,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway
1,2023-05-16,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store
2,2023-07-19,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store
3,2023-04-27,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway
4,2023-06-11,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store
...,...,...,...,...,...,...,...,...
9535,2023-08-30,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway
9536,2023-06-02,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,Takeaway
9537,2023-03-02,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway
9538,2023-12-02,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway
9539,2023-11-07,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store

In [121]:

# all rows where Item is Coffee

df.loc[df.Item == 'Coffee']

df.loc[df['Item']=='Coffee']

,Transaction Date,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
0,2023-09-08,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway
4,2023-06-11,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store
36,2023-06-29,TXN_6688524,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway
72,2023-07-16,TXN_6420335,Coffee,1.0,2.0,2.0,Cash,Takeaway
76,2023-12-09,TXN_3748616,Coffee,2.0,2.0,4.0,Credit Card,In-store
...,...,...,...,...,...,...,...,...
9508,2023-05-24,TXN_6494265,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway
9511,2023-09-12,TXN_9954652,Coffee,2.0,2.0,4.0,Cash,In-store
9530,2023-05-22,TXN_1538510,Coffee,5.0,2.0,10.0,Digital Wallet,Takeaway
9535,2023-08-30,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway
9537,2023-03-02,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway

In [ ]:
# select first five rows of transaction date , item, total spent
df.loc[:4,['Transaction Date','Item','Total Spent']]

  Transaction Date    Item  Total Spent
0       2023-09-08  Coffee          4.0
1       2023-05-16    Cake         12.0
2       2023-07-19  Cookie          8.9
3       2023-04-27   Salad         10.0
4       2023-06-11  Coffee          4.0

In [ ]:
# rows where Payment Method is Digital Wallet
df.loc[df['Payment Method']=='Digital Wallet']

,Transaction Date,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
3,2023-04-27,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway
4,2023-06-11,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store
6,2023-10-06,TXN_4433211,Juice,3.0,3.0,9.0,Digital Wallet,Takeaway
8,2023-07-28,TXN_4717867,Juice,5.0,3.0,15.0,Digital Wallet,Takeaway
9,2023-12-31,TXN_2064365,Sandwich,5.0,4.0,20.0,Digital Wallet,In-store
...,...,...,...,...,...,...,...,...
9534,2023-01-08,TXN_7851634,Juice,4.0,4.0,16.0,Digital Wallet,Takeaway
9535,2023-08-30,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway
9536,2023-06-02,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,Takeaway
9537,2023-03-02,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway
9538,2023-12-02,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway

In [ ]:
# rows where Total Spent is greater than 8.0
df.loc[df['Total Spent']>8.0]

,Transaction Date,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
1,2023-05-16,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store
2,2023-07-19,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store
3,2023-04-27,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway
5,2023-03-31,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,Takeaway
6,2023-10-06,TXN_4433211,Juice,3.0,3.0,9.0,Digital Wallet,Takeaway
...,...,...,...,...,...,...,...,...
9531,2023-02-24,TXN_3897619,Sandwich,3.0,4.0,12.0,Cash,Takeaway
9532,2023-07-05,TXN_2739140,Smoothie,4.0,4.0,16.0,Digital Wallet,In-store
9533,2023-10-20,TXN_4766549,Smoothie,2.0,4.0,8.9,Cash,Takeaway
9534,2023-01-08,TXN_7851634,Juice,4.0,4.0,16.0,Digital Wallet,Takeaway
9539,2023-11-07,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store

In [ ]:
# change Location to Online where Item is Cake
df.loc[df['Item']=='Cake','Location']='Online'

In [ ]:
# select rows from index 10 to 20 and columns from Item to Total Spent
df.loc[10:20,'Item':'Total Spent']

        Item  Quantity  Price Per Unit  Total Spent
10     Salad  5.000000             5.0         25.0
11  Sandwich  2.000000             4.0          8.0
12    Cookie  5.000000             1.0          5.0
13     Juice  2.000000             1.5          3.0
14     Salad  3.000000             5.0         15.0
15  Sandwich  1.000000             4.0          4.0
16     Juice  2.000000             3.0          6.0
17      Cake  5.000000             3.0         15.0
18     Juice  4.000000             3.0         12.0
19  Smoothie  3.028463             4.0         20.0
20  Smoothie  4.000000             4.0         16.0

In [ ]:
# select first five rows
df.iloc[:5]

,Transaction Date,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
0,2023-09-08,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway
1,2023-05-16,TXN_4977031,Cake,4.0,3.0,12.0,Cash,Online
2,2023-07-19,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store
3,2023-04-27,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway
4,2023-06-11,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store

In [ ]:
# select last three rows
df.iloc[-3:]

,Transaction Date,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
9537,2023-03-02,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway
9538,2023-12-02,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway
9539,2023-11-07,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store

In [131]:
# select rows at index positions 2,4,6
df.iloc[[1,3,5]]

,Transaction Date,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
1,2023-05-16,TXN_4977031,Cake,4.0,3.0,12.0,Cash,Online
3,2023-04-27,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway
5,2023-03-31,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,Takeaway

In [ ]:
# select first four rows and columns Item and Quantity
df.iloc[:4,[2,3]]

     Item  Quantity
0  Coffee       2.0
1    Cake       4.0
2  Cookie       4.0
3   Salad       2.0

In [ ]:
# select rows where Location is Takeaway and only show Item and Total Spent columns
df.loc[df['Location']=='Takeaway',['Item','Total Spent']]

          Item  Total Spent
0       Coffee          4.0
3        Salad         10.0
5     Smoothie         20.0
6        Juice          9.0
7     Sandwich         16.0
...        ...          ...
9534     Juice         16.0
9535    Coffee          4.0
9536     Juice          3.0
9537    Coffee          8.0
9538    Cookie          3.0

[5891 rows x 2 columns]

In [ ]:
# increase Price Per Unit by 10% where Item is Coffee
df.loc[df["Item"]=="Coffee",'Price Per Unit']*1.10

0       2.2
4       2.2
36      2.2
72      2.2
76      2.2
       ...
9508    2.2
9511    2.2
9530    2.2
9535    2.2
9537    2.2
Name: Price Per Unit, Length: 1123, dtype: float64

In [137]:
df

,Transaction Date,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
0,2023-09-08,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway
1,2023-05-16,TXN_4977031,Cake,4.0,3.0,12.0,Cash,Online
2,2023-07-19,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store
3,2023-04-27,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway
4,2023-06-11,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store
...,...,...,...,...,...,...,...,...
9535,2023-08-30,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway
9536,2023-06-02,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,Takeaway
9537,2023-03-02,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway
9538,2023-12-02,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway
9539,2023-11-07,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store

In [138]:
df

,Transaction Date,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location
0,2023-09-08,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway
1,2023-05-16,TXN_4977031,Cake,4.0,3.0,12.0,Cash,Online
2,2023-07-19,TXN_4271903,Cookie,4.0,1.0,8.9,Credit Card,In-store
3,2023-04-27,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway
4,2023-06-11,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store
...,...,...,...,...,...,...,...,...
9535,2023-08-30,TXN_7672686,Coffee,2.0,2.0,4.0,Digital Wallet,Takeaway
9536,2023-06-02,TXN_9659401,Juice,3.0,2.9,3.0,Digital Wallet,Takeaway
9537,2023-03-02,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway
9538,2023-12-02,TXN_7695629,Cookie,3.0,2.9,3.0,Digital Wallet,Takeaway
9539,2023-11-07,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store